name: Crystal CI

on:
  push:
  schedule:
      - cron: '0 0 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly]

    runs-on: ubuntu-latest

    steps:
    - name: Download source
      uses: actions/checkout@v2
    - name: Install Crystal
      uses: oprypin/install-crystal@v1
      with:
          crystal: ${{ matrix.crystal }}
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
